_target_: pytorch_lightning.Trainer

accelerator: gpu
devices: 1
max_epochs: 1
profiler: null
log_every_n_steps: 100
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
auto_lr_find: false

# ckpt path
resume_from_checkpoint: null
