_target_: pytorch_lightning.Trainer
accelerator: gpu
devices: 1
max_epochs: 50
# profiler: simple
# profiler:
#   _target_: pytorch_lightning.profiler.PyTorchProfiler
#   on_trace_ready:
#     _taget_: torch.profiler.tensorboard_trace_handler
#     dir_name: ./log/resnet18
log_every_n_steps: 100
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
auto_lr_find: false
# amp_backend: "apex"
# amp_level: "O3"
# ckpt path
# resume_from_checkpoint: falsels

