stages:
  preprocessing:
    cmd: python hfcnn/processing/preprossing_data.py
    deps:
    - data/raw/
    outs:
    - data/processed/train.pkl
    - data/processed/validation.pkl
    - data/processed/test.pkl
  network_construction:
    cmd: python hfcnn/processing/network_construction.py
    deps:
    - hfcnn/default_settings/default_network_construction.yaml
    outs:
    - models/untrained_model.pt
  training:
    cmd: python hfcnn/processing/training.py
    deps:
    - models/untrained_model.pt
    outs:
    - models/training_model.pt
    - models/best_model.pt
