_target_: pytorch_lightning.Trainer

gpus: null
max_epochs: 1000
progress_bar_refresh_rate: 100
profiler: null
log_every_n_steps: 100
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
