# docs: https://pytorch-lightning.readthedocs.io/en/stable/extensions/generated/pytorch_lightning.loggers.CSVLogger.html

csv:
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ./logs
  version: null
  prefix: ""
