# source: https://www.tensorflow.org/tensorboard/
# docs: https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.loggers.tensorboard.html

tensorboard_global:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: ${hydra:runtime.cwd}/outputs
  version: null
  log_graph: true
  default_hp_metric: true
  prefix: ""
  sub_dir: null
