defaults:
  - _self_
  - action: train
  - datamodule: dev
  - model: fully_connected
  - optimizer: adam
  - criterion: mse
  - trainer: default

# disable python warnings
ignore_warnings: false

# global seed
seed: null
