## Preprocessing Settings 

# Train/Validation/Test Split Ratio
# For 80/20 Train/Validation, just return: 
#  - 0.8
# The remainder of the data set is assumed to be validation.

# list of dataframe labels 
label_list:
- 'IA'
# - 'I_tor_A'

# For 70/15/15 Train/Validation/Test, return:
#  - 0.7
#  - 0.15
# The remainder of the data set is assumed to be test. 
train_ratio:
- 0.8

# List containing 2 element lists of [[filter, args], ... ,[filter, args]]
filter_list:
- - data_selection
  - data/raw