defaults:
  - _self_
  - data: default
  - action: train
  - filters: data_selection
  - transforms: half_resolution
  - datamodule: heat_load
  - model: cnn
  - optimizer: adam
  - criterion: mse
  - trainer: default
  - metric: default
  - callback: default
  - logger: both
  - experiment: null
  - override hydra/sweeper: ax

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${dict:${action},name}

# disable python warnings
ignore_warnings: false

# path to original working directory
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
orig_wd: ${hydra:runtime.cwd}