defaults:
  - _self_
  - data: default
  - filters: data_selection
  - features: default
  - transforms: res780x195
  - logger: none
  - scheduler: exponential_lr
  - experiment: null

  # config for hyperparameter optimization
  - hparams_search: null

  # # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

prepare_test: true

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-prepare

# disable python warnings
ignore_warnings: false

# path to original working directory
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
orig_wd: ${hydra:runtime.cwd}
