defaults:
  - _self_
  - data: default
  - action: train
  - filters: data_selection
  - transforms: none
  - datamodule: heat_load
  - model: cnn
  - optimizer: adam
  - criterion: mse
  - trainer: default
  - metric: default
  - callback: default
  - logger: both
  - scheduler: exponential_lr
  - experiment: null
  - override hydra/sweeper: ax

  # config for hyperparameter optimization
  - hparams_search: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${dict:${action},name}

# disable python warnings
ignore_warnings: false

# pretty print config at the start of the run using Rich library
print_config: True

# path to original working directory
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
orig_wd: ${hydra:runtime.cwd}

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

# seed for random number generators in pytorch, numpy and python.random. Default is one of the Munchausen numbers
seed: 3435
