# docs: https://pytorch-lightning.readthedocs.io/en/latest/

_target_: pytorch_lightning.Trainer

max_epochs: 1000
progress_bar_refresh_rate: 100
profiler: null
log_every_n_steps: 100

# gpus: null
# limit_train_batches: 1.0
# limit_val_batches: 1.0
# limit_test_batches: 1.0
