# callback to save the best model according to validation loss
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/loss"
  mode: "min"
  save_weights_only: true
  filename: "{epoch}-{val\/loss:.4f}"
