# docs: https://pytorch-lightning.readthedocs.io/en/stable/extensions/callbacks.html

# callback to save the best model according to validation loss
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/loss"
  mode: "min"
  filename: "{epoch}-{val\/loss:.2f}"

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/loss"
  mode: "min"
