# docs: https://pytorch-lightning.readthedocs.io/en/stable/extensions/callbacks.html

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/loss"
  mode: "min"

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/loss"
  mode: "min"
